# First print your name in the cell below then save this file. (or something nice about your instructor)

In [1]:
# In this cell print your name 
print("Sam Strugger")

Sam Strugger

# Data wrangling with Pandas exercise
* For this exercise we will be using the `listings.csv` data file.

In [2]:
import pandas as pd
import numpy as np

# Load in the data file using `pd.read_csv()`

In [13]:
# Load data here
df = pd.read_csv("../data/listings.csv")

## Exercise 2 - Filtering

Return the following subsets of the dataframe.

1. How many listings are there with a price less than 100? 


2. Find how many listings there are in just Brooklyn.


3. Find how many listings there are in Brooklyn with a price less than 100.


4. Using `.isin()` select anyone that has the host name of Michael, David, John, and Daniel.


5. Create a new column called `adjusted_price` that has $100 added to every listing in Williamsburg.  The prices for all other listings should be the same as the were before. 


6. What % of the rooms are private, and what % of the rooms are shared.  
    * Hint, use `.value_counts()`

In [40]:
# 1. How many listings are there with a price less than 100? 

print(len(df[df["price"] < 100]))

22778

In [29]:
# 2. Make a new DataFrame of listings in Brooklyn named `df_bk` 
# and find how many listings in just Brooklyn.

df_bk = df[df["neighbourhood_group"] == "Brooklyn"]

print(len(df_bk))

18632

In [35]:
# 3. Find how many listings there are in Brooklyn with a price less than 100.
print(
    len(df_bk[df_bk["price"] < 100])
)

10473

In [45]:
# 4. Using `.isin()` select anyone that has the host name of Michael, David, John, and Daniel.
# How many total are there that have those names
host_names = {"Michael", "David", "John", "Daniel"}

condition = df["host_name"].isin(host_names)

print(len(df[condition]))

1258

In [52]:
# 5. Create a new column called `adjusted_price` that has $100 added to every listing in Williamsburg.  
# The prices for all other listings should be the same as the were before. 

mask = df["neighbourhood"] == "Williamsburg"
df["adjusted_price"] = df["price"]
df["adjusted_price"] = np.where(mask, df["adjusted_price"]+100, df["adjusted_price"])

print(df[df["neighbourhood"] == "Williamsburg"].value_counts())

id        name                                               host_id    host_name      neighbourhood_group  neighbourhood  latitude  longitude  room_type        price  minimum_nights  number_of_reviews  last_review  reviews_per_month  calculated_host_listings_count  availability_365  adjusted_price
6848      Only 2 stops to Manhattan studio                   15991      Allen & Irina  Brooklyn             Williamsburg   40.70837  -73.95352  Entire home/apt  109    2               181                2020-03-16   1.32               1                               0                 209               1
7801      Sweet and Spacious Brooklyn Loft                   21207      Chaya          Brooklyn             Williamsburg   40.71842  -73.95718  Entire home/apt  299    3               9                  2011-12-28   0.07               1                               337               399               1
14290     * ORIGINAL BROOKLYN LOFT *                         56104      James          Brooklyn             Williamsburg   40.70420  -73.93560  Entire home/apt  131    3               95                 2020-05-28   0.73               1                               164               231               1
14377     Williamsburg 1 bedroom Apartment                   56512      Joanna         Brooklyn             Williamsburg   40.70881  -73.95930  Entire home/apt  175    10              113                2020-01-24   0.87               1                               165               275               1
15385     Very, very cozy place                              60252      Cristina       Brooklyn             Williamsburg   40.71185  -73.96204  Private room     80     7               49                 2020-02-07   0.39               1                               229               180               1
                                                                                                                                                                                                                                                                                                              ..
43847857  Perfect Williamsburg Studio in Brand New Building  350711081  Julian         Brooklyn             Williamsburg   40.70947  -73.96831  Entire home/apt  118    20              1                  2020-07-22   1.00               2                               336               218               1
43855371  A cozy room in Prime Williamsburg                  374503     Claudia        Brooklyn             Williamsburg   40.71454  -73.94661  Private room     45     3               5                  2020-08-14   3.06               2                               5                 145               1
44032283  Huge 1 Bedroom Williamsburg Loft, Brooklyn, NYC    81158596   Matthew        Brooklyn             Williamsburg   40.70796  -73.95394  Entire home/apt  147    1               5                  2020-07-30   5.00               1                               0                 247               1
44085758  Willy Nilly 1 Bed + Sleeper Sofa + Crazy Roofdeck  353668375  Lynn           Brooklyn             Williamsburg   40.71401  -73.96333  Entire home/apt  180    3               4                  2020-07-27   3.08               1                               322               280               1
44151723  Minimalist room w/ A/C,  gym access and city view  179017459  Douglas        Brooklyn             Williamsburg   40.71030  -73.93886  Private room     65     1               2                  2020-08-10   2.00               1                               178               165               1
Name: count, Length: 2744, dtype: int64

In [60]:
# 6. What % of the rooms are private, and what % of the rooms are shared.  

percents = df["room_type"].value_counts(normalize=True) * 100
print(percents[["Private room", "Shared room"]])

room_type
Private room    45.444581
Shared room      2.121349
Name: proportion, dtype: float64

# Exercise 3 - Grouping

1. Using `groupby`, count how many listings are in each neighbourhood_group.


2. Using `groupby`, find the mean price for each of the neighbourhood_groups. 


3. Using `groupby` and `.agg()`, find the min and max price for each of the neighbourhood_groups. 


4. Using `groupby`, find the median price for each room type in each neighbourhood_group.


5. Using `groupby` and `.agg()`, find the count, min, max, mean, median, and std of the prices for each room type in each neighbourhood_group.

In [68]:
# 1. Using `groupby`, count how many listings are in each neighbourhood_group.
gb_ng = df.groupby("neighbourhood_group")
gb_ng.count()

,id,name,host_id,host_name,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365,adjusted_price
neighbourhood_group,,,,,,,,,,,,,,,,
Bronx,1183,1181,1183,1183,1183,1183,1183,1183,1183,1183,1183,957,957,1183,1183,1183
Brooklyn,18632,18626,18632,18624,18632,18632,18632,18632,18632,18632,18632,14865,14865,18632,18632,18632
Manhattan,20580,20570,20580,20555,20580,20580,20580,20580,20580,20580,20580,15197,15197,20580,20580,20580
Queens,5791,5791,5791,5789,5791,5791,5791,5791,5791,5791,5791,4513,4513,5791,5791,5791
Staten Island,341,341,341,341,341,341,341,341,341,341,341,284,284,341,341,341

In [69]:
# 2. Using `groupby`, find the mean price for each of the neighbourhood_groups.

gb_ng["price"].mean()

neighbourhood_group
Bronx             92.751479
Brooklyn         120.225258
Manhattan        191.880466
Queens            99.754965
Staten Island    110.947214
Name: price, dtype: float64

In [ ]:
# 2.5. Using `groupby`, find the mean price for each room_type. 
gb_rt = df.groupby("room_type")
gb_rt["price"].mean()

room_type
Entire home/apt    199.395950
Hotel room         275.015075
Private room        91.453084
Shared room         87.063830
Name: price, dtype: float64

In [72]:
# 3. Using `groupby` and `.agg()`, find the min and max price for each of the neighbourhood_groups. 
gb_ng["price"].agg(["max", "min"])

                       max  min
neighbourhood_group
Bronx                 1404   16
Brooklyn             10000    0
Manhattan            10000    0
Queens               10000    0
Staten Island         1200   19

In [79]:
# 4. Using `groupby`, find the mean price for each room_type in each neighbourhood_group.

gb_rtng = df.groupby(["neighbourhood_group", "room_type"])
gb_rtng["price"].mean()

neighbourhood_group  room_type
Bronx                Entire home/apt    138.004819
                     Private room        68.419668
                     Shared room         66.391304
Brooklyn             Entire home/apt    171.587687
                     Hotel room         147.300000
                     Private room        71.291189
                     Shared room         57.870091
Manhattan            Entire home/apt    231.335572
                     Hotel room         292.515670
                     Private room       128.277069
                     Shared room        111.735084
Queens               Entire home/apt    150.168900
                     Hotel room         139.058824
                     Private room        69.972564
                     Shared room         89.891892
Staten Island        Entire home/apt    151.720930
                     Private room        70.312883
                     Shared room         46.000000
Name: price, dtype: float64

In [81]:
# 5. Using `groupby` and `.agg()`, find the count, min, max, mean, median, and std of the prices 
# for each room type in each neighbourhood_group.

gb_rtng["price"].agg(["count", "min", "max", "mean", "median", "std"])

                                     count  min    max        mean  median  \
neighbourhood_group room_type
Bronx               Entire home/apt    415   25   1404  138.004819   103.0
                    Private room       722   16    700   68.419668    55.0
                    Shared room         46   20    800   66.391304    44.0
Brooklyn            Entire home/apt   9112   20  10000  171.587687   135.0
                    Hotel room          30    0    399  147.300000   129.0
                    Private room      9159   10   2500   71.291189    60.0
                    Shared room        331   15   1500   57.870091    36.0
Manhattan           Entire home/apt  12209    0  10000  231.335572   165.0
                    Hotel room         351    0   2211  292.515670   210.0
                    Private room      7601   10  10000  128.277069    80.0
                    Shared room        419   10  10000  111.735084    60.0
Queens              Entire home/apt   2090   10  10000  150.168900   115.0
                    Hotel room          17    0    249  139.058824   149.0
                    Private room      3499   18   9000   69.972564    55.0
                    Shared room        185   14   3000   89.891892    40.0
Staten Island       Entire home/apt    172   39   1200  151.720930   111.0
                    Private room       163   20    800   70.312883    55.0
                    Shared room          6   19     82   46.000000    38.0

                                            std
neighbourhood_group room_type
Bronx               Entire home/apt  126.032106
                    Private room      57.337866
                    Shared room      114.442703
Brooklyn            Entire home/apt  236.732843
                    Hotel room        91.153206
                    Private room      69.023165
                    Shared room       92.217618
Manhattan           Entire home/apt  410.306439
                    Hotel room       315.924085
                    Private room     448.677306
                    Shared room      502.728868
Queens              Entire home/apt  252.606739
                    Hotel room        50.743806
                    Private room     163.814468
                    Shared room      275.675158
Staten Island       Entire home/apt  147.518392
                    Private room      70.759593
                    Shared room       28.446441

# Load, Merge, and Export files.
1. Load the `prices.csv` and the `n_listings.csv`
    * Having an error..? Inspect the actual csv file if you're having trouble

2. Do join that keeps all the records for each table.
    * Neighbourhood groups should include ['Bronx', 'Brooklyn', 'Manhattan', 'Queens', 'Staten Island',
       'LongIsland']

       
3. Save your joined csv as `joined.csv` into the data folder. 


4. Load your saved table and see if it looks the same or different that the DataFrame you used to create it.

In [90]:
# 1. Load the `prices.csv` and the `n_listings.csv`
df_n = pd.read_csv("../data/n_listings.csv", sep = ';')
df_p = pd.read_csv("../data/prices.csv", skipinitialspace=True)

In [92]:
# 2. Do join that keeps all the records for each table.
new_df = pd.merge(df_n, df_p, how = "outer")

new_df

  neighbourhood_group  n_listings  mean_price
0               Bronx      1183.0   92.751479
1            Brooklyn     18632.0  120.225258
2          LongIsland      4121.0         NaN
3           Manhattan     20580.0  191.880466
4              Queens         NaN   99.754965
5       Staten Island         NaN  110.947214

In [93]:
# 3. Save your joined csv as `joined.csv` into the data folder. 
new_df.to_csv('joined.csv', index=False)

In [94]:
# 4. Load your newly saved file, see if it looks the same.  If not, try saving with argument `index=False`
new_df_again = pd.read_csv("joined.csv")
new_df_again

  neighbourhood_group  n_listings  mean_price
0               Bronx      1183.0   92.751479
1            Brooklyn     18632.0  120.225258
2          LongIsland      4121.0         NaN
3           Manhattan     20580.0  191.880466
4              Queens         NaN   99.754965
5       Staten Island         NaN  110.947214

# Extra Credit
Every question below this cell is extra credit and optional.

### 2. (Very Easy) Find other cool Panda packages / add ons and show us what they can do well. And how you installed them.

### 3. (Medium) Use the grammys.csv data for the next section of questions.

1. Who was won Album of the Year in 2016?


2. Who won Best Rap Album in 2009?


3. How many awards was Kendrick Lamar nomiated for, and how many did he win...?

### (Hard) Load the Game Logs for 2022 and add the column names using a dictionary.  
* [Link to the data page](https://www.retrosheet.org/gamelogs/)
* [Link to the column names](https://procatinator.com/)
* haha, gotta find them yourself!

### (Extra Hard) Download the files for the past 5 years into a new folder and add them all into one data frame using pandas, then save that new file.
* Try to not hard code in the file names. We want to do this programmatically because what if we want to add new/more file names in the future.