# Fall 2024 Data Science Track: Week 2 - Data Cleaning Exercise

## Packages, Packages, Packages!

Import *all* the things here! You need the standard stuff: `pandas` and `numpy`.

If you got more stuff you want to use, add them here too. 🙂

In [ ]:
# Install pandas and numpy if the active Python environment does not have them. Using Python venv is recommended when you are doing so.
%pip install pandas numpy

In [1]:
# Import here.

import pandas as pd
import numpy as np

## Introduction

With the packages out of the way, now you will be working with the following data sets:

* `food_coded.csv`: [Food choices](https://www.kaggle.com/datasets/borapajo/food-choices?select=food_coded.csv) from Kaggle
* `Ask A Manager Salary Survey 2021 (Responses) - Form Responses 1.tsv`: [Ask A Manager Salary Survey 2021 (Responses)](https://docs.google.com/spreadsheets/d/1IPS5dBSGtwYVbjsfbaMCYIWnOuRmJcbequohNxCyGVw/view?&gid=1625408792) as *Tab Separated Values (.tsv)* from Google Docs

Each one poses different challenges. But you’ll―of course―overcome them with what you learned in class! 😉

## Food Choices Data Set

### Load the Data

Load the Food choices data set into a new variable, `df_food`.

In [5]:
# Load the Food choices data set.

food_data_set_path = '../data/food_coded.csv'

df_food = pd.read_csv(food_data_set_path)

### Explore the Data

How much data did you just load?

In [6]:
# Count by hand. (lol kidding)
len(df_food)

125

In [8]:
# Try to print or display it nicely.
print("Rows:", df_food.shape[0])
print("Columns:", df_food.shape[1])

Rows: 125
Columns: 61

What are the columns and their types in this data set?

In [9]:
# Show the column names and their types.
pd.DataFrame(df_food.dtypes)

                        0
GPA                   str
Gender              int64
breakfast           int64
calories_chicken    int64
calories_day      float64
...                   ...
type_sports           str
veggies_day         int64
vitamins            int64
waffle_calories     int64
weight                str

[61 rows x 1 columns]

In [10]:
pd.set_option("display.max_rows", 100) # Set pandas to render up to 100 rows first. Default caps to 10 and takes the middle chunk out to make the DataFrame fit.

# Try to display the column information as a nice pandas DataFrame.
column_info = pd.DataFrame({
    "Column": df_food.columns,
    "Data Type": df_food.dtypes
})

column_info

                                                    Column Data Type
GPA                                                    GPA       str
Gender                                              Gender     int64
breakfast                                        breakfast     int64
calories_chicken                          calories_chicken     int64
calories_day                                  calories_day   float64
calories_scone                              calories_scone   float64
coffee                                              coffee     int64
comfort_food                                  comfort_food       str
comfort_food_reasons                  comfort_food_reasons       str
comfort_food_reasons_coded      comfort_food_reasons_coded   float64
cook                                                  cook   float64
comfort_food_reasons_coded.1  comfort_food_reasons_coded.1     int64
cuisine                                            cuisine   float64
diet_current                                  diet_current       str
diet_current_coded                      diet_current_coded     int64
drink                                                drink   float64
eating_changes                              eating_changes       str
eating_changes_coded                  eating_changes_coded     int64
eating_changes_coded1                eating_changes_coded1     int64
eating_out                                      eating_out     int64
employment                                      employment   float64
ethnic_food                                    ethnic_food     int64
exercise                                          exercise   float64
father_education                          father_education   float64
father_profession                        father_profession       str
fav_cuisine                                    fav_cuisine       str
fav_cuisine_coded                        fav_cuisine_coded     int64
fav_food                                          fav_food   float64
food_childhood                              food_childhood       str
fries                                                fries     int64
fruit_day                                        fruit_day     int64
grade_level                                    grade_level     int64
greek_food                                      greek_food     int64
healthy_feeling                            healthy_feeling     int64
healthy_meal                                  healthy_meal       str
ideal_diet                                      ideal_diet       str
ideal_diet_coded                          ideal_diet_coded     int64
income                                              income   float64
indian_food                                    indian_food     int64
italian_food                                  italian_food     int64
life_rewarding                              life_rewarding   float64
marital_status                              marital_status   float64
meals_dinner_friend                    meals_dinner_friend       str
mother_education                          mother_education   float64
mother_profession                        mother_profession       str
nutritional_check                        nutritional_check     int64
on_off_campus                                on_off_campus   float64
parents_cook                                  parents_cook     int64
pay_meal_out                                  pay_meal_out     int64
persian_food                                  persian_food   float64
self_perception_weight              self_perception_weight   float64
soup                                                  soup   float64
sports                                              sports   float64
thai_food                                        thai_food     int64
tortilla_calories                        tortilla_calories   float64
turkey_calories                            turkey_calories     int64
type_sports                                    type_sports       str
veggies_day                                    veggies_day     int64
vitamins                                          vitamins     int64
waffle_calories                            waffle_calories     int64
weight                                              weight       str

### Clean the Data

Perhaps we’d like to know more another day, but the team is really interested in just the relationship between calories (`calories_day`) and weight. …and maybe gender.

Can you remove the other columns? (Assign the result to a new variable, `df_food_col_subset`.)

In [12]:
# Remove ‘em.

df_food = df_food.dropna()
df_food

,GPA,Gender,breakfast,calories_chicken,calories_day,calories_scone,coffee,comfort_food,comfort_food_reasons,comfort_food_reasons_coded,...,soup,sports,thai_food,tortilla_calories,turkey_calories,type_sports,veggies_day,vitamins,waffle_calories,weight
1,3.654,1,1,610,3.0,420.0,2,"chocolate, chips, ice cream","Stress, bored, anger",1.0,...,1.0,1.0,2,725.0,690,Basketball,4,2,900,155
2,3.3,1,1,720,4.0,420.0,2,"frozen yogurt, pizza, fast food","stress, sadness",1.0,...,1.0,2.0,5,1165.0,500,none,5,1,900,I'm not answering this.
4,3.5,1,1,720,2.0,420.0,2,"Ice cream, chocolate, chips","Stress, boredom, cravings",1.0,...,1.0,1.0,4,940.0,500,Softball,4,2,760,190
6,3.8,2,1,610,3.0,420.0,2,"Chocolate, ice cream, french fries, pretzels","stress, boredom",1.0,...,1.0,1.0,5,940.0,690,soccer,4,1,1315,180
7,3.3,1,1,720,3.0,420.0,1,"Ice cream, cheeseburgers, chips.",I eat comfort food when im stressed out from s...,1.0,...,1.0,2.0,1,725.0,500,none,4,2,1315,137
9,3.3,1,1,430,3.0,315.0,2,"Mac and cheese, chocolate, and pasta","Stress, anger and sadness",1.0,...,1.0,1.0,4,580.0,345,field hockey,5,1,900,125
10,3.5,1,1,610,3.0,980.0,2,"Pasta, grandma homemade chocolate cake anythin...",Boredom,2.0,...,1.0,1.0,2,940.0,345,soccer,5,2,900,116
11,3.904,1,1,720,4.0,420.0,2,"chocolate, pasta, soup, chips, popcorn","sadness, stress, cold weather",3.0,...,1.0,1.0,5,940.0,500,Running,5,1,900,110
12,3.4,2,1,430,3.0,420.0,2,"Cookies, popcorn, and chips","Sadness, boredom, late night snack",3.0,...,2.0,1.0,3,940.0,500,Soccer and basketball,3,2,575,264
13,3.6,1,1,610,3.0,420.0,2,"ice cream, cake, chocolate","stress, boredom, special occasions",1.0,...,1.0,1.0,5,1165.0,850,intramural volleyball,5,2,1315,123
14,3.1,2,1,610,3.0,420.0,2,"Pizza, fruit, spaghetti, chicken and Potatoes","Friends, environment and boredom",2.0,...,1.0,1.0,4,940.0,500,Hockey,5,1,900,185
17,3.6,2,1,430,3.0,980.0,2,"chips, cookies, ice cream",I usually only eat comfort food when I'm bored...,2.0,...,1.0,1.0,3,940.0,500,hockey,4,2,900,170
18,3.4,1,1,720,3.0,980.0,1,"Chocolate, ice crea","Sadness, stress",3.0,...,2.0,2.0,1,1165.0,690,dancing,5,1,1315,135
20,3.3,2,1,610,3.0,980.0,2,"Fast food, pizza, subs","happiness, satisfaction",7.0,...,1.0,1.0,1,1165.0,850,Soccer,3,2,1315,175
22,3.7,2,1,610,3.0,420.0,1,"burgers, chips, cookies","sadness, depression",3.0,...,1.0,1.0,4,940.0,850,tennis soccer gym,3,1,1315,185
23,3.7,2,2,610,3.0,420.0,2,"Chilli, soup, pot pie",Stress and boredom,1.0,...,1.0,1.0,4,940.0,690,Gaelic Football,4,1,1315,185
25,2.8,1,2,720,3.0,420.0,2,"chocolate, ice cream/milkshake, cookies",boredom,2.0,...,1.0,1.0,3,1165.0,690,Ice hockey,3,2,760,125
26,3.7,2,1,610,2.0,420.0,1,"Chips, ice cream, microwaveable foods","Boredom, lazyniss",2.0,...,2.0,1.0,2,1165.0,850,Hockey,3,2,1315,160
27,3,2,1,610,4.0,980.0,2,"Chicken fingers, pizza",Boredom,2.0,...,1.0,1.0,3,1165.0,500,Lacrosse,5,1,1315,175
31,4,2,1,610,3.0,420.0,2,"chips and dip, pepsi,","stres, boredom, and nighttime",1.0,...,2.0,2.0,4,940.0,690,none organized,5,1,1315,205
34,3.65,1,1,610,3.0,420.0,2,"french fries, chips, ice cream","boredom, stressed, sad",2.0,...,1.0,1.0,3,940.0,345,softball,4,1,1315,150
35,3,1,1,610,2.0,420.0,2,"mac n cheese, peanut butter and banana sandwic...",Boredom usually,2.0,...,1.0,1.0,2,940.0,690,Lacrosse,5,2,760,150
37,3.4,1,1,720,4.0,420.0,2,"chocolate, chips, candy",Stress,1.0,...,1.0,1.0,5,940.0,500,Dancing,4,2,1315,170
38,3.89,1,1,610,3.0,980.0,2,"chocolate, popcorn, ice cream","boredom, stress",2.0,...,1.0,1.0,2,1165.0,690,Lacrosse,3,2,1315,150
40,3.4,2,1,430,3.0,315.0,1,"Pizza, Ice cream, fries, cereal, cookies",Usually if I'm sad or depressed.,3.0,...,1.0,1.0,3,940.0,500,wrestling,4,2,760,140
44,3.2,1,1,610,4.0,420.0,2,"Potato chips, ice cream, chocolate, cookies","Stress, boredom, craving",1.0,...,1.0,1.0,5,725.0,500,Volleyball,5,1,760,170
46,3.8,2,1,430,2.0,420.0,1,"popcorn, chips, candy, & fries","sadness, boredom, & anger",3.0,...,1.0,1.0,3,725.0,345,soccer,4,2,900,168
51,3.3,2,1,610,4.0,980.0,1,Burger,Lazy,5.0,...,1.0,1.0,5,1165.0,500,Hockey,4,1,1315,185
54,3.5,2,1,610,3.0,420.0,2,"peanut butter sandwich, pretzals, garlic bread","stress, anger and boredom",1.0,...,1.0,1.0,4,940.0,690,hockey,5,1,900,165
56,3.8,2,1,720,4.0,315.0,2,"Pizza, Ice Cream, Chicken Wings",I usually only eat comfort foods when I am bor...,2.0,...,1.0,1.0,5,1165.0,500,Hockey,5,1,1315,175
57,2.8,1,1,610,4.0,980.0,2,Pizza chocolate chips bagels ice Capps,Just cause,9.0,...,2.0,1.0,2,725.0,345,softball,4,1,1315,140
58,3.5,1,1,610,3.0,420.0,2,"Chocolate, ice cream, pasta","Stress, boredom, sadness",1.0,...,1.0,1.0,5,1165.0,690,Skiing,5,1,1315,155
60,3.6,1,1,610,4.0,420.0,2,"peanut butter, dessets, pretzels.","Sadness, boredom, lonely.",3.0,...,1.0,1.0,1,1165.0,690,Water polo and running,5,1,1315,135
62,3.9,2,1,610,4.0,980.0,2,"ice cream, cookies, ice cream","boredom, sadness",2.0,...,1.0,1.0,2,1165.0,850,Ice Hockey,4,1,1315,210
64,3.5,1,1,610,3.0,420.0,1,"cookies, nutella, ice cream, coffee, fruit","Bordem, happiness, sadness",2.0,...,2.0,1.0,3,940.0,500,Volleyball,5,1,760,140
67,3.6,1,1,610,2.0,420.0,1,"Ice cream, cake, mozzarella sticks, pierogies",Boredom,2.0,...,1.0,1.0,2,940.0,690,"Recreational Basketball, Equestrian Team",5,2,1315,144 lbs
68,3.2,1,1,430,3.0,315.0,1,"Chips, Mac and cheese, pizza, French fries","Stress, sadness, bored",1.0,...,1.0,1.0,4,725.0,500,soccer,5,2,760,145
70,3.73,1,1,610,3.0,980.0,2,"Broccoli, spaghetti squash, quinoa, and grille...","Bad day, bored, sadness",2.0,...,1.0,1.0,5,1165.0,500,Rec Volleyball,5,1,1315,140
73,3.79 bitch,2,1,720,4.0,420.0,2,"Chips, ice cream","Boredom, stress",2.0,...,1.0,1.0,2,1165.0,850,baseball,4,1,1315,200
75,3,1,1,610,3.0,420.0,2,"mac and cheese, potato soup, ice cream, chips ...","sadness, stressed, boredom",3.0,...,1.0,2.0,4,940.0,500,I danced in high school,4,1,900,120
76,3.7,1,2,610,3.0,420.0,1,"chocolate, pizza, and mashed potatoes",boredom and stress,2.0,...,2.0,1.0,1,1165.0,690,horse back riding,2,2,1315,150
77,3.1,2,2,265,2.0,420.0,1,Pizza cookies steak,Boredom comfort hunger,2.0,...,2.0,1.0,2,725.0,345,Basketball,2,2,900,200
78,3,1,1,720,3.0,420.0,2,"chocolate, fruit, and ice cream","stress, boredom",1.0,...,1.0,1.0,3,580.0,345,competitive skiing,4,1,1315,135
79,3.9,2,1,720,3.0,420.0,2,Chips sweets popcorn,Boredom,2.0,...,1.0,1.0,5,1165.0,850,"Rowing, Running, and Cycling",4,2,1315,145
81,3.5,1,2,610,3.0,420.0,1,"cake, French fries, chicken nuggets","boredom, sadness",2.0,...,2.0,1.0,4,725.0,500,softball and basketball,2,2,900,190
84,3.83,1,1,720,3.0,420.0,2,"Pasta dishes, Cheesecake, Pancakes","Sadness, Loneliness, Boredom",3.0,...,1.0,1.0,5,725.0,690,Collegiate Water Polo,5,1,760,167
85,2.6,1,1,265,3.0,315.0,2,"Ice cream, pizza, cookies",Mostly Stress,1.0,...,1.0,2.0,3,580.0,500,None right now,4,1,760,140
86,3,1,1,610,3.0,420.0,2,"Chinese food, moes, sponge candy, homemade las...","boredom, sadness",2.0,...,1.0,1.0,4,580.0,500,"volleyball, lacrosse",4,1,900,190
87,3.2,2,1,720,3.0,420.0,1,"pizza, pasta, mac and cheese",when i am sad or craving,3.0,...,1.0,1.0,1,1165.0,690,field hockey,4,1,1315,155
91,3.8,1,2,610,2.0,420.0,2,"Macaroni and cheese, chicken noodle soup, pizza",Boredom and stress,2.0,...,1.0,2.0,1,725.0,500,crew,1,2,900,135
96,3.92,2,1,430,3.0,420.0,2,"Ice cream, cake, pop, pizza, and milkshakes.","Happiness, sadness, celebration.",7.0,...,1.0,2.0,3,725.0,500,Soccer,2,1,900,210
103,3.7,1,1,610,3.0,420.0,2,"dark chocolate, terra chips, reese's cups(dark...","Anxiousness, watching TV I desire ""comfort food""",8.0,...,1.0,2.0,3,725.0,345,"When I can, rarely though play pool, darts, an...",5,1,760,130

In [ ]:
# Is there a second way to remove columns?

del df_food["ColumnName"]

In [ ]:
# 🚀 Extra credit: What about a third way to remove columns?

df_food.pop("ColumnName")

What about `NaN`s? How many are there?

In [13]:
# Count ‘em.

df_food.isna().sum()

GPA                             0
Gender                          0
breakfast                       0
calories_chicken                0
calories_day                    0
calories_scone                  0
coffee                          0
comfort_food                    0
comfort_food_reasons            0
comfort_food_reasons_coded      0
cook                            0
comfort_food_reasons_coded.1    0
cuisine                         0
diet_current                    0
diet_current_coded              0
drink                           0
eating_changes                  0
eating_changes_coded            0
eating_changes_coded1           0
eating_out                      0
employment                      0
ethnic_food                     0
exercise                        0
father_education                0
father_profession               0
fav_cuisine                     0
fav_cuisine_coded               0
fav_food                        0
food_childhood                  0
fries                           0
fruit_day                       0
grade_level                     0
greek_food                      0
healthy_feeling                 0
healthy_meal                    0
ideal_diet                      0
ideal_diet_coded                0
income                          0
indian_food                     0
italian_food                    0
life_rewarding                  0
marital_status                  0
meals_dinner_friend             0
mother_education                0
mother_profession               0
nutritional_check               0
on_off_campus                   0
parents_cook                    0
pay_meal_out                    0
persian_food                    0
self_perception_weight          0
soup                            0
sports                          0
thai_food                       0
tortilla_calories               0
turkey_calories                 0
type_sports                     0
veggies_day                     0
vitamins                        0
waffle_calories                 0
weight                          0
dtype: int64

In [ ]:
# 🚀 Extra credit: Try to display the NaN sums as a nice pandas DataFrame.

df_food.isna().sum().sum()

In [ ]:
# 🚀 Extra credit: You can turn one line of code into multiple lines of code using a backslash as a continuation character to break up what would otherwise be a long line.

We gotta remove those `NaN`s―the entire row.

In [ ]:
# Drop ‘em in-place.
df_food = df_food.dropna()

In [ ]:
# 🚀 Extra credit: Check if the in-place modifications also affected the original DataFrame, df_food. 🙂

But what about the weird non-numeric values in the column obviously meant for numeric data?

Notice the data type of that column from when you got the types of all the columns?

If only we could convert the column to a numeric type and drop the rows with invalid values. 🤔

In [17]:
df_food["weight"] = pd.to_numeric(
    df_food["weight"], errors="coerce"
)

df_food.dropna(subset=["weight"], inplace=True)

Now this data seems reasonably clean for our purposes! 😁

Let’s save it somewhere to be shipped off to another teammate. 💾

In [18]:
# Savey save!

df_food.to_csv("data/food_cleaned.csv", index=False)

OSError: Cannot save file into a non-existent directory: 'data'

In [20]:
# 🚀 Extra credit: Load and print a few lines of the saved file as plain text.

df_food.head()

,GPA,Gender,breakfast,calories_chicken,calories_day,calories_scone,coffee,comfort_food,comfort_food_reasons,comfort_food_reasons_coded,...,soup,sports,thai_food,tortilla_calories,turkey_calories,type_sports,veggies_day,vitamins,waffle_calories,weight
1,3.654,1,1,610,3.0,420.0,2,"chocolate, chips, ice cream","Stress, bored, anger",1.0,...,1.0,1.0,2,725.0,690,Basketball,4,2,900,155.0
4,3.5,1,1,720,2.0,420.0,2,"Ice cream, chocolate, chips","Stress, boredom, cravings",1.0,...,1.0,1.0,4,940.0,500,Softball,4,2,760,190.0
6,3.8,2,1,610,3.0,420.0,2,"Chocolate, ice cream, french fries, pretzels","stress, boredom",1.0,...,1.0,1.0,5,940.0,690,soccer,4,1,1315,180.0
7,3.3,1,1,720,3.0,420.0,1,"Ice cream, cheeseburgers, chips.",I eat comfort food when im stressed out from s...,1.0,...,1.0,2.0,1,725.0,500,none,4,2,1315,137.0
9,3.3,1,1,430,3.0,315.0,2,"Mac and cheese, chocolate, and pasta","Stress, anger and sadness",1.0,...,1.0,1.0,4,580.0,345,field hockey,5,1,900,125.0

## Ask a Manager Salary Survey 2021 (Responses) Data Set

### Load the Data

Load the Ask A Manager Salary Survey 2021 (Responses) data set into a new variable, `df_salary`.

In [21]:
# Load the Ask A Manager Salary Survey 2021 (Responses) data set.

salary_data_set_path = '../data/Ask A Manager Salary Survey 2021 (Responses) - Form Responses 1.tsv'
df_salary = pd.read_csv(salary_data_set_path, sep='\t')

Was that hard? 🙃

### Explore

You know the drill.

How much data did you just load?

In [22]:
# Count by hand. I’m dead serious.

len(df_salary)

28062

What are the columns and their types?

In [29]:
# Show the column names and their types.

df_salary.dtypes

Timestamp                                                                                                                                                                                                                                   str
How old are you?                                                                                                                                                                                                                            str
What industry do you work in?                                                                                                                                                                                                               str
Job title                                                                                                                                                                                                                                   str
If your job title needs additional context, please clarify here:                                                                                                                                                                            str
What is your annual salary? (You'll indicate the currency in a later question. If you are part-time or hourly, please enter an annualized equivalent -- what you would earn if you worked the job 40 hours a week, 52 weeks a year.)        str
How much additional monetary compensation do you get, if any (for example, bonuses or overtime in an average year)? Please only include monetary compensation here, not the value of benefits.                                          float64
Please indicate the currency                                                                                                                                                                                                                str
If "Other," please indicate the currency here:                                                                                                                                                                                              str
If your income needs additional context, please provide it here:                                                                                                                                                                            str
What country do you work in?                                                                                                                                                                                                                str
If you're in the U.S., what state do you work in?                                                                                                                                                                                           str
What city do you work in?                                                                                                                                                                                                                   str
How many years of professional work experience do you have overall?                                                                                                                                                                         str
How many years of professional work experience do you have in your field?                                                                                                                                                                   str
What is your highest level of education completed?                                                                                                                                                                                          str
What is your gender?                                                                                                                                                                                                                        str
What is your race? (Choose all that apply.)                                                                                                                                                                                                 str
dtype: object

Oh… Ugh! Give these columns easier names to work with first. 🙄

In [30]:
# Rename ‘em in-place.
# Non-binding suggestions: timestamp, age, industry, title, title_context, salary, additional_compensation, currency, other_currency, salary_context, country, state, city, total_yoe, field_yoe, highest_education_completed	gender, race

df_salary.columns = ['timestamp', 'age', 'industry', 'title', 'title_context', 'salary', 'additional_compensation', 'currency', 'other_currency', 'salary_context', 'country', 'state', 'city', 'total_yoe', 'field_yoe', 'highest_education_completed', 'gender', 'race']

It’s a lot, and that should not have been easy. 😏

You’re going to have a gander at the computing/tech subset first because thats *your* industry. But first, what value corresponds to that `industry`?

In [32]:
# List the unique industries and a count of their instances.

df_salary.industry.value_counts()

industry
Computing or Tech                               4699
Education (Higher Education)                    2464
Nonprofits                                      2419
Health care                                     1896
Government and Public Administration            1889
                                                ...
Undergrad student                                  1
Concrete Construction                              1
I'm currently a student and don't have a job       1
Student                                            1
Wine & Spirits                                     1
Name: count, Length: 1219, dtype: int64

That value among the top 5 is what you’re looking for innit? Filter out all the rows not in that industry and save it into a new variable, `df_salary_tech`.

In [33]:
# Filtery filter.
df_salary_tech = df_salary[df_salary.industry == 'Computing or Tech'].copy()
df_salary_tech.head()

,timestamp,age,industry,title,title_context,salary,additional_compensation,currency,other_currency,salary_context,country,state,city,total_yoe,field_yoe,highest_education_completed,gender,race
1,4/27/2021 11:02:22,25-34,Computing or Tech,Change & Internal Communications Manager,NaN,"54,600",4000.0,GBP,NaN,NaN,United Kingdom,NaN,Cambridge,8 - 10 years,5-7 years,College degree,Non-binary,White
8,4/27/2021 11:03:01,45-54,Computing or Tech,Systems Analyst,Data developer/ETL Developer,"112,000",10000.0,USD,NaN,NaN,US,Missouri,St. Louis,21 - 30 years,21 - 30 years,College degree,Woman,White
43,4/27/2021 11:04:04,25-34,Computing or Tech,Principal Software Engineer,NaN,"187,500",5000.0,USD,NaN,NaN,United States,Pennsylvania,Pittsburgh,8 - 10 years,5-7 years,College degree,Woman,White
44,4/27/2021 11:04:04,25-34,Computing or Tech,Intelligence Analyst,NaN,"110,000",20000.0,USD,NaN,"Around 20,000 a year in stock",USA,Virginia,"Arlington, VA",8 - 10 years,8 - 10 years,Master's degree,Man,White
46,4/27/2021 11:04:07,35-44,Computing or Tech,Mobile developer,NaN,"144,600",2500.0,USD,NaN,NaN,USA,Massachusetts,Boston,5-7 years,5-7 years,PhD,Woman,White

Do a sanity check by counting.

In [34]:
# Sanity check count.
len(df_salary_tech)

4699

We are very interested in salary figures. But how many dollars 💵 is a euro 💶 or a pound 💷? That sounds like a problem for another day. 🫠

For now, let’s just look at U.S. dollars (`'USD'`).

In [35]:
# Filtery filter (in place) for just the jobs that pay in USD!

df_salary_tech.drop(
    df_salary_tech[df_salary_tech.currency != "USD"].index,
    inplace=True
)

df_salary_tech.currency.value_counts()

currency
USD    3777
Name: count, dtype: int64

What we really want know is how each U.S. state pays in tech. What value in `country` represents the United States of America?

In [36]:
# We did filter for USD, so if we do a count of each unique country in descending count order, the relevant value(s) should show up at the top.

df_salary_tech.country.value_counts()

country
United States                1576
USA                          1222
US                            412
U.S.                          108
United States of America       90
United States                  68
Usa                            59
USA                            56
usa                            28
United states                  23
united states                  14
Us                             12
us                              9
U.S.A.                          7
United States of America        7
Israel                          5
Canada                          4
U.S.                            2
United State of America         2
Unite States                    2
Australia                       2
UnitedStates                    2
India                           2
U.S                             2
Usa                             2
United States Of America        2
Spain                           2
Brazil                          2
United Kingdom                  2
united States                   2
New Zealand                     2
Poland                          2
France                          2
U.S.A                           2
United States of america        2
US                              1
Uniyed states                   1
America                         1
Puerto Rico                     1
U.s.                            1
 US                             1
United State                    1
Cuba                            1
Danmark                         1
Italy                           1
International                   1
United Stated                   1
Remote (philippines)            1
Singapore                       1
Uruguay                         1
Mexico                          1
Canada                          1
United Stateds                  1
ISA                             1
singapore                       1
Pakistan                        1
Netherlands                     1
China                           1
San Francisco                   1
Romania                         1
United STates                   1
Japan                           1
United Stares                   1
Australian                      1
Denmark                         1
Jamaica                         1
Unites States                   1
Thailand                        1
U.S.A                           1
Colombia                        1
denmark                         1
Ghana                           1
Nigeria                         1
ss                              1
Nigeria                         1
Burma                           1
Name: count, dtype: int64

### Clean the Data

Well, we can’t get our answers with what we currently have, so you’ll have to make some changes.

Let’s not worry about anything below the first 5 values for now. Convert the top 5 to a single canonical value―say, `'US'`, which is nice and short.

In [37]:
# Replace them all in-place with 'US'.
df_salary_tech.country = df_salary_tech.country.map(lambda country: country.strip())
df_salary_tech["country"] = df_salary_tech["country"].replace(
    [
        "United States",
        "USA",
        "US",
        "U.S.",
        "United States of America",
        "united states",
        "United states",
        "Usa",
        "usa",
        "us",
        "Us",
        "U.S.A.",
        "Unite States",
        "UnitedStates",
        "U.S",
        "United State of America",
        "U.S.A",
        "United States Of America",
        "united States",
        "United States of america",
        "U.s.",
        "United State"
    ],
    "US"
)

Have a look at the count of each unique country again now.

In [38]:
# Count again.

df_salary_tech.country.value_counts()

country
US                      3716
Canada                     5
Israel                     5
Australia                  2
India                      2
Spain                      2
Brazil                     2
United Kingdom             2
New Zealand                2
Poland                     2
France                     2
Nigeria                    2
Uniyed states              1
America                    1
Puerto Rico                1
Cuba                       1
Danmark                    1
Italy                      1
International              1
United Stated              1
Remote (philippines)       1
Singapore                  1
Uruguay                    1
Mexico                     1
United Stateds             1
ISA                        1
singapore                  1
Pakistan                   1
Netherlands                1
China                      1
San Francisco              1
Romania                    1
United STates              1
Japan                      1
United Stares              1
Australian                 1
Denmark                    1
Jamaica                    1
Unites States              1
Thailand                   1
Colombia                   1
denmark                    1
Ghana                      1
ss                         1
Burma                      1
Name: count, dtype: int64

Did you notice anything interesting?

In [ ]:
# 🚀 Extra credit: Resolve [most of] those anomalous cases too without exhaustively taking every variant literally into account.

In [ ]:

# 🚀 Extra credit: If you’ve resolved it, let’s see how well you did by counting the number of instances of each unique value.

It’s looking good so far. Let’s find out the minimum, mean, and maximum (in that order) salary by state, sorted by the mean in descending order.

In [40]:
# Find the minimum, mean, and maximum salary in USD by U.S. state.

df_salary.groupby("STATE_COLUMN")["SALARY_COLUMN"].agg(["min", "mean", "max"])

KeyError: 'STATE_COLUMN'

 Well, pooh! We forgot that `salary` isn’t numeric. Something wrong must be fixed. 🤔

In [41]:
# Fix it in-place.
df_salary["SalaryUSD"] = pd.to_numeric(
    df_salary["SalaryUSD"], errors="coerce"
)

df_salary.dropna(subset=["SalaryUSD"], inplace=True)

df_salary.groupby("State")["SalaryUSD"].agg(["min", "mean", "max"])

KeyError: 'SalaryUSD'

Let’s try that again.

In [52]:
# Try it again. Yeah!
df_salary["salary"] = pd.to_numeric(
    df_salary["salary"], errors="coerce"
)
df_salary.dropna(subset=["salary"], inplace=True)
df_salary["timestamp"] = pd.to_datetime(df_salary["timestamp"])

df_salary_filtered = df_salary[
    df_salary["timestamp"].dt.year.isin([2021, 2022, 2023])
]

df_salary_filtered.groupby("state")["salary"].agg(["min", "mean", "max"])

,min,mean,max
state,,,
Alabama,0.0,68424.250000,350000.0
"Alabama, California",29120.0,29120.000000,29120.0
"Alabama, Oregon",50000.0,50000.000000,50000.0
Alaska,47840.0,82652.533333,200000.0
Arizona,26500.0,86190.060241,380000.0
"Arizona, California",90000.0,90000.000000,90000.0
"Arizona, New York",72000.0,72000.000000,72000.0
Arkansas,28080.0,67005.440000,145000.0
California,0.0,113612.700405,520000.0
"California, Colorado",176000.0,176000.000000,176000.0
"California, District of Columbia, Illinois, Iowa, Maryland, Minnesota",130000.0,130000.000000,130000.0
"California, Illinois, Massachusetts, North Carolina, South Carolina, Virginia",85000.0,85000.000000,85000.0
"California, Maryland",81500.0,81500.000000,81500.0
"California, New York",48000.0,48000.000000,48000.0
"California, Oregon",200000.0,200000.000000,200000.0
Colorado,65.0,87244.088608,200000.0
Connecticut,0.0,89062.647059,270000.0
Delaware,35000.0,103455.555556,220000.0
"Delaware, Pennsylvania",35000.0,35000.000000,35000.0
District of Columbia,40.0,110124.701835,1250000.0
"District of Columbia, Virginia",80900.0,101700.000000,115000.0
"District of Columbia, Washington",35000.0,35000.000000,35000.0
Florida,150.0,79460.919786,645000.0
"Florida, New Hampshire, Wisconsin",70000.0,70000.000000,70000.0
Georgia,0.0,85621.421965,860000.0
Hawaii,32460.0,65270.000000,142000.0
Idaho,38.0,72550.500000,300000.0
Illinois,0.0,88123.874608,340000.0
"Illinois, North Carolina",52000.0,52000.000000,52000.0
Indiana,105.0,80178.446809,925000.0
"Indiana, Massachusetts",132000.0,132000.000000,132000.0
Iowa,13000.0,68420.595238,142000.0
"Iowa, Nebraska",48000.0,48000.000000,48000.0
Kansas,52.0,68686.189189,167000.0
"Kansas, Missouri",64000.0,64000.000000,64000.0
Kentucky,0.0,66174.876923,175000.0
Louisiana,20000.0,75958.368421,200000.0
"Louisiana, Washington",117000.0,117000.000000,117000.0
Maine,26000.0,65832.914894,173000.0
Maryland,0.0,89366.050000,353200.0
"Maryland, New York",14000.0,14000.000000,14000.0
"Maryland, Virginia",78000.0,78000.000000,78000.0
Massachusetts,155.0,99872.434343,400000.0
"Massachusetts, New Hampshire",60000.0,60000.000000,60000.0
Michigan,55.0,77597.371069,240000.0
"Michigan, Texas, Washington",340000.0,340000.000000,340000.0
Minnesota,40.0,83155.450262,215000.0
Mississippi,30000.0,59661.538462,125000.0
"Mississippi, Missouri",110000.0,110000.000000,110000.0
Missouri,70.0,67334.321739,200000.0
Montana,19200.0,71369.272727,145000.0
Nebraska,18000.0,79161.062500,224000.0
Nevada,55.0,82215.480000,165000.0
New Hampshire,55.0,68619.194444,208000.0
New Jersey,14850.0,129931.842975,5000044.0
"New Jersey, New York",135000.0,138666.666667,141000.0
"New Jersey, Pennsylvania",40200.0,91600.000000,143000.0
New Mexico,78.0,74496.760000,177000.0
New York,80.0,106875.209459,590000.0
"New York, Oregon, Vermont",53000.0,53000.000000,53000.0
"New York, Virginia",65000.0,65000.000000,65000.0
North Carolina,15000.0,77154.964706,165000.0
North Dakota,0.0,62217.333333,96000.0
Ohio,36.0,78993.337778,954000.0
Oklahoma,25000.0,62752.586207,180000.0
Oregon,0.0,90191.924419,230000.0
"Oregon, Washington",52900.0,52900.000000,52900.0
Pennsylvania,0.0,80780.869403,252000.0
"Pennsylvania, Rhode Island",62000.0,62000.000000,62000.0
Rhode Island,27040.0,73162.631579,150000.0
South Carolina,0.0,63141.648649,223000.0
South Dakota,33000.0,46625.000000,60000.0
Tennessee,24000.0,77698.921053,275000.0
Texas,0.0,88761.618280,300000.0
Utah,28000.0,91444.551020,576000.0
Vermont,32000.0,64075.578947,120000.0
Virginia,57.0,96219.045455,1300000.0
Washington,72.0,98022.110727,300000.0
West Virginia,0.0,52754.375000,120000.0
Wisconsin,1.0,83000.628788,920000.0
Wyoming,42500.0,59906.333333,98000.0

That did the trick! Now let’s narrow this to data 2021 and 2022 just because (lel). *(Hint: that timestamp column may not be a temporal type right now.)*

In [54]:
# Filter the data to within 2021, 2022, or 2023, saving the DataFrame to a new variable, and generate the summary again.
df_salary["timestamp"] = pd.to_datetime(df_salary["timestamp"])

df_salary_filtered = df_salary[
    df_salary["timestamp"].dt.year.isin([2021, 2022, 2023])
]

## Bonus

Clearly, we do not have enough data to produce useful figures for the level of specificity you’ve now reached. What do you notice about Delaware and West Virginia?

Let’s back out a bit and return to `df_salary` (which was the loaded data with renamed columns but *sans* filtering).

### Bonus #0

Apply the same steps as before to `df_salary`, but do not filter for any specific industry. Do perform the other data cleaning stuff, and get to a point where you can generate the minimum, mean, and maximum by state.

### Bonus #1

This time, format the table output nicely (*$12,345.00*) without modifying the values in the `DataFrame`. That is, `df_salary` should be identical before versus after running your code.

(*Hint: if you run into an error about `jinja2` perhaps you need to `pip install` something.*)

### Bonus #2

Filter out the non-single-states (e.g., `'California, Colorado'`) in the most elegant way possible (i.e., *not* by blacklisting all the bad values).

### Bonus #3

Show the quantiles instead of just minimum, mean, and maximum―say 0%, 5%, 25%, 50%, 75%, 95%, and 100%. Outliers may be deceiving.

Sort by whatever interests you―like say the *50th* percentile.

And throw in a count by state too. It would be interesting to know how many data points contribute to the figures for each state. (*Hint: your nice formatting from Bonus #1 might not work this time around.* 😜)