# Fall 2024 Data Science Track: Week 2 - Data Cleaning Exercise

## Packages, Packages, Packages!

Import *all* the things here! You need the standard stuff: `pandas` and `numpy`.

If you got more stuff you want to use, add them here too. 🙂

In [ ]:
# Install pandas and numpy if the active Python environment does not have them. Using Python venv is recommended when you are doing so.
%pip install pandas numpy

In [2]:
# Import here.
import pandas as pd
import numpy as np

## Introduction

With the packages out of the way, now you will be working with the following data sets:

* `food_coded.csv`: [Food choices](https://www.kaggle.com/datasets/borapajo/food-choices?select=food_coded.csv) from Kaggle
* `Ask A Manager Salary Survey 2021 (Responses) - Form Responses 1.tsv`: [Ask A Manager Salary Survey 2021 (Responses)](https://docs.google.com/spreadsheets/d/1IPS5dBSGtwYVbjsfbaMCYIWnOuRmJcbequohNxCyGVw/view?&gid=1625408792) as *Tab Separated Values (.tsv)* from Google Docs

Each one poses different challenges. But you’ll―of course―overcome them with what you learned in class! 😉

## Food Choices Data Set

### Load the Data

Load the Food choices data set into a new variable, `df_food`.

In [2]:
# Load the Food choices data set.
df_food = pd.read_csv('../data/food_coded.csv')

### Explore the Data

How much data did you just load?

In [4]:
# Count by hand. (lol kidding)
len(df_food)

125

In [5]:
# Try to print or display it nicely.
print(f"DataFrame length: {len(df_food)}")

DataFrame length: 125

What are the columns and their types in this data set?

In [6]:
# Show the column names and their types.
df_food.dtypes

GPA                     str
Gender                int64
breakfast             int64
calories_chicken      int64
calories_day        float64
                     ...
type_sports             str
veggies_day           int64
vitamins              int64
waffle_calories       int64
weight                  str
Length: 61, dtype: object

In [7]:
pd.set_option("display.max_rows", 100) # Set pandas to render up to 100 rows first. Default caps to 10 and takes the middle chunk out to make the DataFrame fit.

# Try to display the column information as a nice pandas DataFrame.
pd.DataFrame(data=df_food.dtypes, columns=["data types"])

                             data types
GPA                                 str
Gender                            int64
breakfast                         int64
calories_chicken                  int64
calories_day                    float64
calories_scone                  float64
coffee                            int64
comfort_food                        str
comfort_food_reasons                str
comfort_food_reasons_coded      float64
cook                            float64
comfort_food_reasons_coded.1      int64
cuisine                         float64
diet_current                        str
diet_current_coded                int64
drink                           float64
eating_changes                      str
eating_changes_coded              int64
eating_changes_coded1             int64
eating_out                        int64
employment                      float64
ethnic_food                       int64
exercise                        float64
father_education                float64
father_profession                   str
fav_cuisine                         str
fav_cuisine_coded                 int64
fav_food                        float64
food_childhood                      str
fries                             int64
fruit_day                         int64
grade_level                       int64
greek_food                        int64
healthy_feeling                   int64
healthy_meal                        str
ideal_diet                          str
ideal_diet_coded                  int64
income                          float64
indian_food                       int64
italian_food                      int64
life_rewarding                  float64
marital_status                  float64
meals_dinner_friend                 str
mother_education                float64
mother_profession                   str
nutritional_check                 int64
on_off_campus                   float64
parents_cook                      int64
pay_meal_out                      int64
persian_food                    float64
self_perception_weight          float64
soup                            float64
sports                          float64
thai_food                         int64
tortilla_calories               float64
turkey_calories                   int64
type_sports                         str
veggies_day                       int64
vitamins                          int64
waffle_calories                   int64
weight                              str

### Clean the Data

Perhaps we’d like to know more another day, but the team is really interested in just the relationship between calories (`calories_day`) and weight. …and maybe gender.

Can you remove the other columns? (Assign the result to a new variable, `df_food_col_subset`.)

In [3]:
# Remove ‘em.
condition = ['calories_day', 'weight', "Gender"]
df_food_col_subset = df_food[condition]
df_food_col_subset.head()

   calories_day                    weight  Gender
0           NaN                       187       2
1           3.0                       155       1
2           4.0  I'm not answering this.        1
3           3.0             Not sure, 240       1
4           2.0                       190       1

In [11]:
# Is there a second way to remove columns?
df_food_col_subset = df_food.loc[:, ['calories_day', 'weight', 'Gender']]
df_food_col_subset.head()

   calories_day                    weight  Gender
0           NaN                       187       2
1           3.0                       155       1
2           4.0  I'm not answering this.        1
3           3.0             Not sure, 240       1
4           2.0                       190       1

In [ ]:
# 🚀 Extra credit: What about a third way to remove columns?

What about `NaN`s? How many are there?

In [14]:
# Count ‘em.
df_food_col_subset.isna().sum()

calories_day    19
weight           2
Gender           0
dtype: int64

In [15]:
# 🚀 Extra credit: Try to display the NaN sums as a nice pandas DataFrame.
pd.DataFrame(data=df_food_col_subset.isna().sum(), columns=['NaN(s)'])

              NaN(s)
calories_day      19
weight             2
Gender             0

In [16]:
# 🚀 Extra credit: You can turn one line of code into multiple lines of code using a backslash as a continuation character to break up what would otherwise be a long line.
pd.DataFrame( \
            data=df_food_col_subset.isna().sum(), \
            columns=['NaN(s)'])

              NaN(s)
calories_day      19
weight             2
Gender             0

We gotta remove those `NaN`s―the entire row.

In [4]:
# Drop ‘em in-place.
df_food_col_subset.dropna(inplace=True)
df_food_col_subset.isna().sum()

calories_day    0
weight          0
Gender          0
dtype: int64

In [18]:
# 🚀 Extra credit: Check if the in-place modifications also affected the original DataFrame, df_food. 🙂
df_food.isna().sum()

GPA                  2
Gender               0
breakfast            0
calories_chicken     0
calories_day        19
                    ..
type_sports         26
veggies_day          0
vitamins             0
waffle_calories      0
weight               2
Length: 61, dtype: int64

But what about the weird non-numeric values in the column obviously meant for numeric data?

Notice the data type of that column from when you got the types of all the columns?

If only we could convert the column to a numeric type and drop the rows with invalid values. 🤔

In [ ]:
# Fix that in-place.
df_food_col_subset['weight'] = pd.to_numeric(df_food_col_subset['weight'], errors='coerce')
df_food_col_subset.dropna(inplace=True)
df_food_col_subset = df_food_col_subset.astype({'calories_day': float, 'weight': float, 'Gender': str})
# I don't know which of the numbers(1 and 2) in Gender is 'Male' or 'Female' so I will not replace those values
df_food_col_subset.head()

   calories_day  weight Gender
1           3.0   155.0      1
4           2.0   190.0      1
5           3.0   190.0      1
6           3.0   180.0      2
7           3.0   137.0      1

Now this data seems reasonably clean for our purposes! 😁

Let’s save it somewhere to be shipped off to another teammate. 💾

In [ ]:
# Savey save!
df_food_col_subset.to_csv('../data/cleaned_food_coded_subset.csv', index=False)

In [18]:
# 🚀 Extra credit: Load and print a few lines of the saved file as plain text.
df = pd.read_csv('../data/cleaned_food_coded_subset.csv')
df.head()

   calories_day  weight  Gender
0           3.0   155.0       1
1           2.0   190.0       1
2           3.0   190.0       1
3           3.0   180.0       2
4           3.0   137.0       1

## Ask a Manager Salary Survey 2021 (Responses) Data Set

### Load the Data

Load the Ask A Manager Salary Survey 2021 (Responses) data set into a new variable, `df_salary`.

In [3]:
# Load the Ask A Manager Salary Survey 2021 (Responses) data set.
df_salary = pd.read_csv('../data/Ask A Manager Salary Survey 2021 (Responses) - Form Responses 1.tsv', sep='\t')

Was that hard? 🙃

### Explore

You know the drill.

How much data did you just load?

In [23]:
# Count by hand. I’m dead serious.
len(df_salary)

28062

What are the columns and their types?

In [24]:
# Show the column names and their types.
df_salary.dtypes

Timestamp                                                                                                                                                                                                                                   str
How old are you?                                                                                                                                                                                                                            str
What industry do you work in?                                                                                                                                                                                                               str
Job title                                                                                                                                                                                                                                   str
If your job title needs additional context, please clarify here:                                                                                                                                                                            str
What is your annual salary? (You'll indicate the currency in a later question. If you are part-time or hourly, please enter an annualized equivalent -- what you would earn if you worked the job 40 hours a week, 52 weeks a year.)        str
How much additional monetary compensation do you get, if any (for example, bonuses or overtime in an average year)? Please only include monetary compensation here, not the value of benefits.                                          float64
Please indicate the currency                                                                                                                                                                                                                str
If "Other," please indicate the currency here:                                                                                                                                                                                              str
If your income needs additional context, please provide it here:                                                                                                                                                                            str
What country do you work in?                                                                                                                                                                                                                str
If you're in the U.S., what state do you work in?                                                                                                                                                                                           str
What city do you work in?                                                                                                                                                                                                                   str
How many years of professional work experience do you have overall?                                                                                                                                                                         str
How many years of professional work experience do you have in your field?                                                                                                                                                                   str
What is your highest level of education completed?                                                                                                                                                                                          str
What is your gender?                                                                                                                                                                                                                        str
What is your race? (Choose all that apply.)                                                                                                                                                                                                 str
dtype: object

Oh… Ugh! Give these columns easier names to work with first. 🙄

In [4]:
# Rename ‘em in-place.
# Non-binding suggestions: timestamp, age, industry, title, title_context, salary, additional_compensation, currency, other_currency, salary_context, country, state, city, total_yoe, field_yoe, highest_education_completed	gender, race
df_salary.columns = ['timestamp', 'age', 'industry', 'title', \
                     'title_context', 'salary', 'additional_compensation', \
                     'currency', 'other_currency', 'salary_context', \
                     'country', 'state', 'city', 'total_yoe', 'field_yoe', \
                     'highest_education_completed', 'gender', 'race']
df_salary.dtypes

timestamp                          str
age                                str
industry                           str
title                              str
title_context                      str
salary                             str
additional_compensation        float64
currency                           str
other_currency                     str
salary_context                     str
country                            str
state                              str
city                               str
total_yoe                          str
field_yoe                          str
highest_education_completed        str
gender                             str
race                               str
dtype: object

It’s a lot, and that should not have been easy. 😏

You’re going to have a gander at the computing/tech subset first because thats *your* industry. But first, what value corresponds to that `industry`?

In [5]:
# List the unique industries and a count of their instances.
df_salary['industry'].value_counts()

industry
Computing or Tech                               4699
Education (Higher Education)                    2464
Nonprofits                                      2419
Health care                                     1896
Government and Public Administration            1889
                                                ...
Undergrad student                                  1
Concrete Construction                              1
I'm currently a student and don't have a job       1
Student                                            1
Wine & Spirits                                     1
Name: count, Length: 1219, dtype: int64

That value among the top 5 is what you’re looking for innit? Filter out all the rows not in that industry and save it into a new variable, `df_salary_tech`.

In [5]:
# Filtery filter.
df_salary_tech = df_salary[df_salary['industry'] == 'Computing or Tech']

Do a sanity check by counting.

In [9]:
# Sanity check count.
len(df_salary_tech)

4699

We are very interested in salary figures. But how many dollars 💵 is a euro 💶 or a pound 💷? That sounds like a problem for another day. 🫠

For now, let’s just look at U.S. dollars (`'USD'`).

In [6]:
# Filtery filter (in place) for just the jobs that pay in USD!
df_USD_salary_tech = df_salary_tech[df_salary_tech['currency'] == 'USD']
df_USD_salary_tech.head()

,timestamp,age,industry,title,title_context,salary,additional_compensation,currency,other_currency,salary_context,country,state,city,total_yoe,field_yoe,highest_education_completed,gender,race
8,4/27/2021 11:03:01,45-54,Computing or Tech,Systems Analyst,Data developer/ETL Developer,"112,000",10000.0,USD,NaN,NaN,US,Missouri,St. Louis,21 - 30 years,21 - 30 years,College degree,Woman,White
43,4/27/2021 11:04:04,25-34,Computing or Tech,Principal Software Engineer,NaN,"187,500",5000.0,USD,NaN,NaN,United States,Pennsylvania,Pittsburgh,8 - 10 years,5-7 years,College degree,Woman,White
44,4/27/2021 11:04:04,25-34,Computing or Tech,Intelligence Analyst,NaN,"110,000",20000.0,USD,NaN,"Around 20,000 a year in stock",USA,Virginia,"Arlington, VA",8 - 10 years,8 - 10 years,Master's degree,Man,White
46,4/27/2021 11:04:07,35-44,Computing or Tech,Mobile developer,NaN,"144,600",2500.0,USD,NaN,NaN,USA,Massachusetts,Boston,5-7 years,5-7 years,PhD,Woman,White
47,4/27/2021 11:04:09,35-44,Computing or Tech,Product Design Director,NaN,"200,850",40000.0,USD,NaN,NaN,USA,North Carolina,Chapel Hill,11 - 20 years,11 - 20 years,College degree,Woman,White

What we really want know is how each U.S. state pays in tech. What value in `country` represents the United States of America?

In [17]:
# We did filter for USD, so if we do a count of each unique country in descending count order, the relevant value(s) should show up at the top.
df_USD_salary_tech['country'].value_counts()

country
United States               1576
USA                         1222
US                           412
U.S.                         108
United States of America      90
                            ...
Ghana                          1
Nigeria                        1
ss                             1
Nigeria                        1
Burma                          1
Name: count, Length: 76, dtype: int64

### Clean the Data

Well, we can’t get our answers with what we currently have, so you’ll have to make some changes.

Let’s not worry about anything below the first 5 values for now. Convert the top 5 to a single canonical value―say, `'US'`, which is nice and short.

In [7]:
# Replace them all in-place with 'US'.
df_USD_salary_tech.replace(to_replace=['United States of America', 'United States', 'USA', 'U.S.'], value='US', inplace=True)
df_USD_salary_tech['country'].value_counts()

country
US                3408
United States       68
Usa                 59
USA                 56
usa                 28
                  ...
Ghana                1
Nigeria              1
ss                   1
Nigeria              1
Burma                1
Name: count, Length: 72, dtype: int64

Have a look at the count of each unique country again now.

In [8]:
# Count again.
df_USD_salary_tech.replace(to_replace=['United States ', 'Usa', 'USA ', 'usa'], value='US', inplace=True)
df_USD_salary_tech['country'].value_counts()

country
US               3619
United states      23
united states      14
Us                 12
us                  9
                 ...
Ghana               1
Nigeria             1
ss                  1
Nigeria             1
Burma               1
Name: count, Length: 68, dtype: int64

Did you notice anything interesting?

In [ ]:
# 🚀 Extra credit: Resolve [most of] those anomalous cases too without exhaustively taking every variant literally into account.

In [ ]:

# 🚀 Extra credit: If you’ve resolved it, let’s see how well you did by counting the number of instances of each unique value.

It’s looking good so far. Let’s find out the minimum, mean, and maximum (in that order) salary by state, sorted by the mean in descending order.

In [ ]:
# Find the minimum, mean, and maximum salary in USD by U.S. state.
df_USD_salary_tech.groupby('state')['salary'].agg(['min', 'mean', 'max']).sort_values(by='mean', ascending=False)

 Well, pooh! We forgot that `salary` isn’t numeric. Something wrong must be fixed. 🤔

In [12]:
# Fix it in-place.
df_USD_salary_tech['salary'] = pd.to_numeric(df_USD_salary_tech['salary'], errors='coerce')

Let’s try that again.

In [13]:
# Try it again. Yeah!
df_USD_salary_tech.groupby('state')['salary'].agg(['min', 'mean', 'max']).sort_values(by='mean', ascending=False)

                                  min      mean        max
state
Michigan, Texas, Washington  340000.0  340000.0   340000.0
Florida                       28800.0  210711.0  2600000.0
California, Oregon           200000.0  200000.0   200000.0
California, Colorado         176000.0  176000.0   176000.0
Delaware                     169000.0  169000.0   169000.0
...                               ...       ...        ...
Mississippi                       NaN       NaN        NaN
New York, Texas                   NaN       NaN        NaN
North Dakota                      NaN       NaN        NaN
South Dakota                      NaN       NaN        NaN
Utah, Vermont                     NaN       NaN        NaN

[66 rows x 3 columns]

That did the trick! Now let’s narrow this to data 2021 and 2022 just because (lel). *(Hint: that timestamp column may not be a temporal type right now.)*

In [16]:
# Filter the data to within 2021, 2022, or 2023, saving the DataFrame to a new variable, and generate the summary again.
df_USD_salary_tech_recent = df_USD_salary_tech[df_USD_salary_tech['timestamp'].str.contains('2021|2022|2023')]
df_USD_salary_tech_recent['timestamp']

8        4/27/2021 11:03:01
43       4/27/2021 11:04:04
44       4/27/2021 11:04:04
46       4/27/2021 11:04:07
47       4/27/2021 11:04:09
                ...
27960     5/9/2023 17:57:30
27961    5/28/2023 16:10:53
27971      8/8/2023 7:12:10
27975     9/8/2023 12:35:45
27989    10/26/2023 8:17:05
Name: timestamp, Length: 3764, dtype: str

## Bonus

Clearly, we do not have enough data to produce useful figures for the level of specificity you’ve now reached. What do you notice about Delaware and West Virginia?

Let’s back out a bit and return to `df_salary` (which was the loaded data with renamed columns but *sans* filtering).

### Bonus #0

Apply the same steps as before to `df_salary`, but do not filter for any specific industry. Do perform the other data cleaning stuff, and get to a point where you can generate the minimum, mean, and maximum by state.

### Bonus #1

This time, format the table output nicely (*$12,345.00*) without modifying the values in the `DataFrame`. That is, `df_salary` should be identical before versus after running your code.

(*Hint: if you run into an error about `jinja2` perhaps you need to `pip install` something.*)

### Bonus #2

Filter out the non-single-states (e.g., `'California, Colorado'`) in the most elegant way possible (i.e., *not* by blacklisting all the bad values).

### Bonus #3

Show the quantiles instead of just minimum, mean, and maximum―say 0%, 5%, 25%, 50%, 75%, 95%, and 100%. Outliers may be deceiving.

Sort by whatever interests you―like say the *50th* percentile.

And throw in a count by state too. It would be interesting to know how many data points contribute to the figures for each state. (*Hint: your nice formatting from Bonus #1 might not work this time around.* 😜)